####数据库配置
spring:
  datasource:
    url: jdbc:mysql://172.16.49.129:3306/SpringCloud?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
    database: 0
    timeout: 5000
####打印MyBatias日志
logging:
  level:
    com.ll.member.mapper: DEBUG
