####数据库配置
spring:
  application:
    name: app-member
  datasource:
    url: jdbc:mysql://172.16.49.129:3306/SpringCloud?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
    database: 0
    timeout: 5000
####打印MyBatias日志
logging:
  level:
    com.ll.member.mapper: DEBUG
server:
  port: 8300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka
swagger:
  base-package: com.ll.member.service
  title: SpringCloud2.x构建微服务电商项目-会员服务接口
  description: 该项目“基于SpringCloud2.x构建微服务电商项目
  version: 1.1
  terms-of-service-url: www.baidu.com
  contact:
    name: 刘世林
    email: github.newblushL.com