###服务启动端口号
server:
  port: 80
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-zuul
  datasource:
    url: jdbc:mysql://172.16.49.129:3306/SpringCloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
####打印MyBatias日志
logging:
  level:
    com.ll.member.mapper: DEBUG
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka


### 配置网关反向代理
zuul:
  routes:
    api-a:
      ### 以 /api-weixin/访问转发到微信服务
      path: /api-weixin/**
      serviceId: app-weixin
    api-b:
      ### 以 /api-member/访问转发到会员服务
      path: /api-member/**
      serviceId: app-member
    api-c:
      path: /api-pay/**
      serviceId: app-pay
    api-d:
      path: /public/api-pay/**
      serviceId: app-pay